### ISSUE TITLE
Actions HVAC and Charge

### ISSUE THREAD

**Issue by JeedHome44** [epenet/hassRenaultZE#31]
It's possible to add actions charge and HVAC please?

In the pyze document, we have that:

Writing data
Each of these expects a JSON object body of the form:

{
  "data": {
    "type": "SomeTypeName",
    "attributes": {
      (... the actual data ...)
    }
  }
}

In many cases, you'll be re-POSTing a similar object to that which you received for the corresponding GET method. A success response from the server tends to be the same object you just POSTed, with an ID added. I've listed the required attributes where I know them.

/actions/charge-mode (POST): sets the charge mode. (Type ChargeMode)
action: either schedule_mode or always_charging (possibly a third value - see above)
/actions/hvac-start (POST): Sets the preconditioning timer, or turns on preconditioning immediately. (Type HvacStart)
action: start
targetTemperature: in degrees Celsius. The app is hard-coded to use 21°C.
startDateTime: if supplied, should be of the form YYYY-MM-DDTHH:MM:SSZ - I'm not sure what would happen if you tried to use a different timezone offset. If not supplied, preconditioning will begin immediately.

**Comment by johan12345** [comment]
It is probably possible, but repeatedly asking for it probably doesn't help. Someone needs to dedicate their time to work on this :)

**Comment by JeedHome44** [comment]
I’d like to help but I don’t know how to program.  😞

**Comment by epenet** [comment]
You can try to grab the latest from branch [dev_services](https://github.com/epenet/hassRenaultZE/tree/dev_services).
Please note that there is an extra file required: services.yaml.

Once added and the services restarted, it should have four services added: 
- ac_start:
  -   description: Start A/C on vehicle.
- ac_cancel:
  -   description: Cancel A/C on vehicle.
- charge_start:
  -   description: Start charge on vehicle.
- charge_set_mode:
  -   description: Set charge mode on vehicle.

I have also noticed an issue with the logging in the readme. The platform should be before the entity type:
- valid: custom_components.**renaultze.sensor**: debug
- _invalid: custom_components.**sensor.renaultze**: debug_

**Comment by JeedHome44** [comment]
Great! I will test it now! :)

**Comment by JeedHome44** [comment]
so i have 4 new services:
- renaultze.ac_cancel
- renaultze.ac_start
- renaultze.ac_charge_set_mode
- renaultze.ac_charge_start

to do somethinq, i have to do scripto with it. that's it?

**Comment by JeedHome44** [comment]
i do 4 script. but the script to chenge calendar mode have a probleme.
i want to write that:

service: renaultze.charge_set_mode
entity_id: sensor.zoe40
charge_mode: schedule_mode

Hassio don't want record it

**Comment by JeedHome44** [comment]
i add that in my script.yaml

'1589190413353':
  alias: zoe40_ac_start_now
  sequence:
  - entity_id: sensor.zoe40
    service: renaultze.ac_start
'1589190456408':
  alias: zoe40_ac_cancel
  sequence:
  - entity_id: sensor.zoe40
    service: renaultze.ac_cancel
'1589190499937':
  alias: zoe40_charge_start
  sequence:
  - entity_id: sensor.zoe40
    service: renaultze.charge_start
'1589190593760':
  alias: zoe40_calendrier_on
  sequence:
  - data:
      charge_mode: schedule_mode
    entity_id: sensor.zoe40
    service: renaultze.charge_set_mode

the last script don't work.

**Comment by epenet** [comment]
You can test the services individually inside the UI (https://your-server/developer-tools/service)

I am not familiar with the script.yaml

**Comment by JeedHome44** [comment]
i just test it with the veveloper-tools. i have no error but the calenbdar statut don't change in the statut "charge mode".

**Comment by JeedHome44** [comment]
I tried it out this afternoon. the ac_start function works well. the charge_start function also works well.
if it is started when the zoé is not connected, it takes the calendar off and always_charge.

By cons, I can not put the calendar on schedule_mode with charge_set_mode, i don't know why.

very good job already! a big thank-you!

**Comment by JeedHome44** [comment]
after a reboot, my script work: 

```
'1589206784082':
  alias: zoe40_calendrier_off
  sequence:
  - data:
      charge_mode: always_charging
    entity_id: sensor.zoe40
    service: renaultze.charge_set_mode
```
But this one no:

```
'1589190593760':
  alias: zoe40_calendrier_on
  sequence:
  - data:
      charge_mode: schedule_mode
    entity_id: sensor.zoe40
    service: renaultze.charge_set_mode
```

I think this is a problem with the Renault server and not with your work.

My Zoé goes to the garage on Wednesday, I will ask them because even on the smartphone application, I cannot activate the calendar.

Thank you very much for all your work! I will share it on social networks!

**Comment by JeedHome44** [comment]
hello,

My Zoe has been in the garage.
Everything is OK.
I called Renault R-Link service to tell them that it was impossible to activate the calendar with the application as well as with the API.  They told me they were going to study the problem.

However, in the PyZE API, there is another possible action:

> /actions/charge-schedule (POST): Set a charge schedule. See later. (Type ChargeSchedule)

> The charge scheduler
> Perhaps unsurprisingly, given the need to interoperate with the existing fleet of current Zoes, the charge scheduler functions in exactly the same way, and with the same limitations:
> You must specify exactly one charging period per day, for every day of the week
> Charge start and duration must be in intervals of 15 minutes
> Charge duration must be at least 15 minutes
> Charging periods must not overlap
> Charge start time is specified as a four-character digit string e.g. "0115" (because that's how everyone represents time, right?)
> Charge duration is specified as an integer, rather than a digit string as it was in the previous API

is it possible to add this action?  because I noticed on the MyRenault app that you can activate the calendar only if you change a value.  then we return the previous value and the calendar remains active.  therefore, to really activate the calendar, you must modify a value using this action.

it would therefore be possible, with a Hassio script, to change the calendar data twice to activate it.

**Comment by epenet** [comment]
Yes, I saw the "set schedule" but it seems quite complex to use as you need to create a ChargeSchedule object first, and that pass that to the PyZE API.
I'll have to review how to create this ChargeSchedule object to be able to push it up to PyZE.

**Comment by JeedHome44** [comment]
My exemple calendar:

Monday: Start: 02:00 During: 4 hours
Tuesday: Start: 02:00 During: 4 hours
Wednesday: Start: 02:00 During: 4 hours
Thursday: Start: 02:00 During: 4 hours
Friday: Start: 02:00 During: 4 hours
Saturday: Start: 02:00 During: 4 hours
Sunday: Start: 02:00 During: 4 hours

If I change only:
Monday: Start: 02:00 During: 4,15hours
in MyRenault App. Calendar is activate.

After I change:
Monday: Start: 02:00 During: 4 hours
in MyRenault App. Calendar is active too.

So, why have to do this 2 actions with the action changeSchedule to really activate calendar. If you can do this update, your GitHub will be perfect!

Thank you so much to your job! ;)

**Comment by JeedHome44** [comment]
This file is the solution to add ChargeSchedule no?

https://github.com/jamesremuscat/pyze/blob/develop/src/pyze/api/schedule.py

**Comment by epenet** [comment]
Yes, I knew about this API.
The problem was how to translate human input into a functioning ChargeSchedule object!

I have just pushed some updates onto the dev_services branch for you to test.
Remember that you can test the services individually inside the UI (https://your-server/developer-tools/service)

**Comment by JeedHome44** [comment]
oh great! i test it now! ;)

**Comment by JeedHome44** [comment]
VERY GOOD JOB!!! It's work! I do this script and it activate really calendar in Zoé!

```
'1589476771733':
  alias: zoe40_calendrier_refresh
  sequence:
  - data:
      schedules:
        activated: true
        friday:
          duration: 240
          startTime: T02:00Z
        id: 1
        monday:
          duration: 240
          startTime: T02:00Z
        saturday:
          duration: 240
          startTime: T02:00Z
        sunday:
          duration: 240
          startTime: T02:00Z
        thursday:
          duration: 240
          startTime: T02:00Z
        tuesday:
          duration: 240
          startTime: T02:00Z
        wednesday:
          duration: 240
          startTime: T02:00Z
    entity_id: sensor.zoe40
    service: renaultze.charge_set_schedules
```

Thank you very much!
